//! Widget implementations

mod branch_name_dialog;
mod button;
mod clone_dialog;
pub mod confirm_dialog;
pub mod context_menu;
mod error_dialog;
pub mod file_list;
mod header_bar;
mod merge_dialog;
mod pull_dialog;
mod push_dialog;
mod rebase_dialog;
mod remote_dialog;
mod repo_dialog;
pub mod scrollbar;
pub mod search_bar;
mod settings_dialog;
mod shortcut_bar;
mod tab_bar;
mod text_area;
mod text_input;
mod toast;
mod tooltip;

pub use branch_name_dialog::{BranchNameDialog, BranchNameDialogAction};
pub use button::Button;
pub use clone_dialog::{CloneDialog, CloneDialogAction};
pub use confirm_dialog::{ConfirmDialog, ConfirmDialogAction};
pub use context_menu::{ContextMenu, MenuAction, MenuItem};
pub use error_dialog::ErrorDialog;
pub use file_list::{FileList, FileListAction};
pub use header_bar::{HeaderAction, HeaderBar};
pub use merge_dialog::{MergeDialog, MergeDialogAction, MergeStrategy};
pub use pull_dialog::{PullDialog, PullDialogAction};
pub use push_dialog::{PushDialog, PushDialogAction};
pub use rebase_dialog::{RebaseDialog, RebaseDialogAction};
pub use remote_dialog::{RemoteDialog, RemoteDialogAction};
pub use repo_dialog::{RepoDialog, RepoDialogAction};
pub use settings_dialog::{SettingsDialog, SettingsDialogAction};
pub use shortcut_bar::{ShortcutBar, ShortcutContext};
pub use tab_bar::{TabAction, TabBar};
pub use text_area::TextArea;
pub use text_input::TextInput;
pub use toast::{ToastManager, ToastSeverity};
pub use tooltip::Tooltip;
